################################
# API Manager
autodiscoveryId: "000000"

# Listener
https:
  port: "8083"
################################

openmeteo:
  protocol: "https"
  host: "api.open-meteo.com"
  base-path: "v1"
  path: "forecast"